Add ESLint
studiohyperdrive/nodejs-boilerplate pull request #149
Opened 2019-11-26 17:48 UTC by FabianMeul

2019-12-09 09:45 UTC, tom-odb commented on server/.eslintrc.js
> +		'airbnb-typescript/base',
Is het nodig dat we zowel de airbnb base als de recommended extenden?
Zou verwachten dat die airbnb base min of meer hetzelfde doet, niet?

2019-12-09 09:47 UTC, tom-odb commented on server/tsconfig.paths.json
> +{
kan je dit in een andere pr doen? heeft niets met tslint te maken en weet niet of ik hier wel zo fan van ben (hou dan liever die discussie apart, dan zit deze pr niet geblokkeerd)

2019-12-11 08:21 UTC, bertyhell commented
op windows klaagt hij van line endings. 
```
error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
```

Git checkt bestanden automatisch uit als CRLF en commit ze als LF, dus deze check is niet nodig en kan je disablen?
```
  rules:{
    "linebreak-style": 0
  }
```

2019-12-11 08:22 UTC, bertyhell commented
deze rule disable je best ook, aangezien voor deze repo besloten werd om toch de "I" prefix te gebruiken:
```
error  Interface name must not be prefixed with "I"     @typescript-eslint/interface-name-prefix

```

2019-12-11 08:30 UTC, bertyhell commented
als ik de linter run zonder docker krijg ik nog heel wat lint errors.
```
npm run lint
```

enkele error voorbeelden:
  37:8   error  Missing trailing comma                           comma-dangle
   7:2   error  Type string trivially inferred from a string literal, remove type annotation  @typescript-eslint/no-inferrable-types
    1:80   error  Expected a line break before this closing brace       object-curly-newline
   29:15   error  Expected 'this' to be used by class method 'getAll'   class-methods-use-this
  13:1   error  Dependency cycle detected                        import/no-cycle

2019-12-11 08:35 UTC, bertyhell commented
bij voorkeur geen PR openzetten vanuit jouw fork:master maar een branch aanmaken binnen jouw fork. Dit is wss door die permissie issues, maar als je zelf een branch aanmaakt in je fork dan kunnen we die uitchecken zonder de lokale origin:master te moeten resetten naar fabian:master

2020-01-23 10:27 UTC, nielsbril commented
Ik maak hier maandag tijd voor 🙂

2020-01-23 10:34 UTC, bertyhell requested changes

2024-03-14 18:47 UTC, closed without merging